channels:
  hangoutsChat:
    default:
      # https://developers.google.com/hangouts/chat/how-tos/webhooks
      url: https://chat.googleapis.com/v1/spaces/CHAMGE_ME_SPACE_ID/messages?key=CHANGE_ME_KEY&token=CHANGE_ME_TOKEN
      # thread: CHANGE_ME_THREAD_ID

templates:
  hangoutsChat:
    simpleWebhook:
      type: gotemplate-yaml
      template: |-
        text:
          Hi, <users/all>!!!

          {{ .some.text | toYaml }}
